# Generated by Django 3.1.12 on 2025-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_anonymizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizationjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
